### ISSUE TITLE
Annotate genes with OMIM and Orphanet terms

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/annonars#165]
**Is your feature request related to a problem? Please describe.**
We currently don't have up-to-date and easy-to-use OMIM/Orphanet terms. The dbNSFP data is a bit outdated.

**Describe the solution you'd like**
Import annotations from gene to OMIM and Orphanet data. OMIM to HPO term will then come via viguno.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
Orphanet missing, should be done via [orphapacket](https://github.com/Orphanet/orphapacket).

**Comment by xiamaz** [comment]
Is support for [MONDO](https://mondo.monarchinitiative.org) planned?
