### ISSUE TITLE
Gnomad frequencies are missing for some variants while being in gnomad

### ISSUE THREAD

**Issue by stolpeo** [bihealth/annonars#287]
**Describe the bug**
Some frequencies are available in gnomad but are not returned by annonars.

**To Reproduce**
```
$ curl "localhost:8000/proxy/varfish/annonars/annos/variant?genome_release=grch37&chromosome=17&pos=46019981&reference=G&alternative=C"
{"server_version":"0.24.4","query":{"genome_release":"grch37","chromosome":"17","pos":46019981,"reference":"G","alternative":"C"},"result":{"cadd":null,"dbsnp":null,"dbnsfp":null,"dbscsnv":null,"gnomad_mtdna":null,"gnomad_exomes":null,"gnomad_genomes":null,"helixmtdb":null,"ucsc_conservation":[]}}
```
https://gnomad.broadinstitute.org/variant/17-46019981-G-C?dataset=gnomad_r2_1

**Expected behavior**
Frequencies should be consistent between annonars and gnomad.

**Comment by holtgrewe** [comment]
The variant is not in the reduced-to-exomes dataset currently deployed on our inhouse instance. It is available in the full data as deployed on reev (CC @xiamaz).
